name: Docker Build

on: [push, pull_request]

env:
  OWNER: guitarrapc
  IMAGE_NAME: docker-awscli-kubectl

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build --build-arg VCS_REF=$(git rev-parse --short HEAD) -t ${OWNER}/${IMAGE_NAME}:latest .
